swagger: "2.0"
info:
  description: "Temperature conversion API"
  version: "1.0.0"
  title: "Temperature conversion"
  contact:
    email: "fabricio@veronez.dev"
paths:
  /fahrenheit/{value}/celsius:
    get:
      description: "Convert from Fahrenheit to Celsius"
      produces:
      - "application/json"
      parameters:
      - name: "value"
        in: "path"
        description: "Value that will be converted"
        required: true
        type: "number"
      responses:
        "200":
          description: "Conversion result"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperature"
        "400":
          description: "Bad Input Parameter"

  /celsius/{value}/fahrenheit:
    get:
      description: "Convert from Celsius to Fahrenheit"
      produces:
      - "application/json"
      parameters:
      - name: "value"
        in: "path"
        description: "Value that will be converted"
        required: true
        type: "number"
      responses:
        "200":
          description: "Conversion result"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperature"
        "400":
          description: "Bad Input Parameter"

definitions:
  Temperature:
    type: "object"
    required:
    - "value"
    properties:
      value:
        type: "number"
        example: 500.0
